board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # url요청 맨앞에 posts가 들어오면
    # post 앱 안의 url한테 위임
    path('posts/', include('post.urls'))
]

post/urls.py
from django.urls import path
from . import views

# post:create
app_name = 'post'

urlpatterns = [
    path('',views.list, name='list'),
    path('create/',views.create, name='create'),
    path('<int:id>/detail/',views.detail, name='detail'),
    path('<int:id>/update/',views.update, name='update'),
    path('<int:id>/delete/',views.delete, name='delete'),
    path('model_create/',views.model_create, name='model_create'),
    path('<int:id>/model_update',views.model_update,name='model_update'),
]

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=100)
    authorr = models.CharField(max_length=50, default='temp')
    time = models.DateField(auto_now_add=True)
    usernickname = models.CharField(max_length=50, default='temp')
    
    def __str__(self):
        return self.title
        
        

post/forms.py
from django import forms
from .models import Post
class PostForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={'class':'editable'}
            ))
    
class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

post/views.py
from django.shortcuts import render, redirect, resolve_url
from .forms import PostForm, PostModelForm
from .models import Post

# Create your views here.
def list(request):
    posts = Post.objects.all()
    return render(request,'post/list.html',{'posts':posts})
    
def create(request):
    if request.method == "POST":
        # 저장로직
        form = PostForm(request.POST)
        if form.is_valid():
            # title = form.cleand_data['title']
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            Post.objects.create(title=title,content=content)
            return redirect(resolve_url('post:list'))
    else:
        # 입력할 수 있는 폼 리턴
        form = PostForm()
    return render(request, 'post/create.html',{'form':form})
        
def detail(request,id):
    post = Post.objects.get(id=id)
    return render(request,'post/detail.html',{'post':post})

def update(request,id):
    post = Post.objects.get(id=id)
    if request.method == "POST":
        # 폼을 검증 후 수정 저장 하는 단계
        form = PostForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            # post.update(title=title,content=content)
            post.title = title
            post.content = content
            post.save()
            return redirect(resolve_url('post:detail',id))
    else:
        # 기존의 데이터를 폼에 담아서 사용자에게 전달
        form = PostForm({'title':post.title,'content':post.content})
    return render(request, 'post/update.html',{'form':form,'post':post})

def delete(request,id):
    post = Post.objects.get(id=id)
    post.delete()
    
    return redirect(resolve_url('post:list'))

def model_create(request):
    if request.method == "POST":
        # 저장하는 로직
        pass
    else:
        # 폼을 보여주는 로직
        form = PostModelForm()
        pass
    return render(request,'post/model_create.html',{'form':form})

def model_update(request,id):
    pass

post/templates/post/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
</head>
<body>
    <h1>여기는 base입니다.</h1>
    <a href="{% url 'post:create' %}">글작성</a>
    {%block body_block%}
    {%endblock%}
</body>
</html>

post/templates/post/create.html
{%extends 'post/base.html'%}

{%block body_block%}
    <!--폼을 넣어야 합니다.-->
    <form action="{% url 'post:create' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit"/>
    </form>
    <script>var editor = new MediumEditor('.editable');</script>
    
{%endblock%}

post/templates/post/detail.html
{% extends 'post/base.html' %}

{%block body_block%}
    <a href="{% url 'post:delete' id=post.id %}">삭제</a>
    <a href="{% url 'post:update' id=post.id %}">수정</a>
    <h1>{{post.title}}</h1>
    {{post.content|safe}}
{%endblock%}

post/templates/post/list.html
{%extends 'post/base.html'%}

{%block body_block%}
    <h1>여기는 list 입니다.</h1>
    {%for post in posts%}
        <h1>{{post.title}}</h1>
        <!--<a href="/posts/123/detail/">글보기</a>-->
        <a href="{% url 'post:detail' id=post.id %}">글보기</a>
    {%endfor%}

{%endblock%}

post/templates/post/model_create.html
{%extends 'post/base.html'%}

{%block body_block%}
    {{form}}
{%endblock%}

post/templates/post/update.html
{%extends 'post/base.html'%}

{%block body_block%}
    <form action="{% url 'post:update' id=post.id %}" method='post'>
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
    <script>var editor = new MediumEditor('.editable');</script>
{%endblock%}